### PR TITLE
Feature/registration frontend

### PR DESCRIPTION
**Pull request by NikolaPleicFOI**
PR for [IAP-11](https://airvjezbe-g4.atlassian.net/browse/IAP-11)

Aspects of the feature we should improve on in the future:

- proper testing (default testing framework in android is quite limiting and unwieldy)
- nicer error display (errors appearing below the associated field)
- more convenient architecture for interacting with the server

### CODE REVIEW

**Comment by DFMM11** [comment]
Hello, can we normalize the showing of screenshots of the working page/component when we make a front-end PR?

**Comment by NikolaPleicFOI** [comment]
Found some small problems after creating the initial PR.
Here is a screenshot of the registration page:
image

**Review by DFMM11 — APPROVED** [review]
LGTM!
I would just add a way from the keyboard to pass from field to field. I remember the professor added it in the Pop-Up app and we could reproduce since it helps a lot.
Overall, good Job m8! Is really good :)

**Comment by DMindek** [comment]
Looked over code, LGTM

**Review by DMindek — COMMENTED** [review]
Forgot to assign myself as reviewer, looks good

**Pull request merged**
