### PR TITLE
Feature/registration backend

### PR DESCRIPTION
**Pull request by luis-viegas**
PR for [IAP-10](https://airvjezbe-g4.atlassian.net/browse/IAP-10). This PR successfully closes the sub-task.

Some useful notes:

Register requests should be made to: "localhost:3000/api/v1/register"

An example of a successful request would be: 
`{
    "user": {
        "username": "teste6",
        "email": "teste6@gmail.com",
        "password": "password5!",
        "location": "Portugal"
    }
}`

With the response being:
`{
    "message": "Successfully created a new user."
}`
And, most importantly, the http status code would be "201" indicating successful resource creation.

An example of an unsuccessful request would be:
`{
    "user": {
        "username": "teste4",
        "email": "teste4.com",
        "password": "password",
        "location": "Portugal"
    }
}`

With the response being:
`{
    "email": [
        "has already been taken",
        "is invalid"
    ],
    "username": [
        "has already been taken"
    ],
    "password": [
        "is too short (minimum is 10 characters)",
        "is invalid"
    ]
}`
And, most importantly, the http status code would be "422" meaning unprocessable content.

### CODE REVIEW

**Review by NikolaPleicFOI — APPROVED** [review]
I don't see any obvious faults with the backend, seems well organized and readable.

**Comment by DMindek** [comment]
LGTM

**Comment by DMindek** [comment]
LGTM

**Review by DMindek — APPROVED** [review]
LGTM

**Comment by DMindek** [comment]
Pull request is for wrong branch. Feature branches should be merged into development. Please consult CONTRIBUTING md document.

**Pull request closed without merging**
